config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'homes#top'
  get 'about' => 'homes#about'
  resources :books, only: [:show,:edit,:update,:index,:create]
  resources :users, only: [:show,:edit,:update,:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 75 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true,length: { in: 2..20 }
  validates :introduction,length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

    def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @users =  User.all
    @user = current_user
    @book_new = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_new = Book.new
  end

  def new
  　@book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_new = Book.new
    @book = Book.new
  end

  def create
    @book_new = Book.new
    @books = Book.all
    @user = current_user
    @book = Book.new(list_params)
    @book.user_id = current_user.id
  if @book.save
    flash[:success] = "You have created book successfully."
    redirect_to book_path(@book.id)
  else
    render:new
  end
  end


  def delete
    @book = Book.find(params[:id])
  if  @book.destroy
    redirect_to books_path
  end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
  if  @book.update(list_params)
    redirect_to book_path(@book.id)
  else
    render:edit
  end
  end

  private

  def list_params
    params.require(:book).permit(:title, :body,:user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @books = Book.all
    @user = current_user
    @book_new = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
    @books = @user.books
  end

  def new

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to user_path(@user.id)
  else
    render :new
  end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="error-message" style="color:green">
  <% if @book.errors.any? %>
  <%= @book.errors.count %> Error occurred
    <% @book.errors.full_messages.each do |message| %><br/>
      <%= message %>
    <% end %>
  <% end %>
</div>
<div class="container p-4">
  <div class="row  w-50 mx-auto">
    <div class="col">
      <h1>Editing Book</h1>
        <%= form_with model:@book, local: true do |f| %>
          <div class="book-edit-title pt-2">Title</div>
          <div class="book-edit-title2 pb-2"><%= f.text_field :title %></div>
          <div class="book-edit-body pt-2">Opinion</div>
          <div class="book-edit-body1 pb-2"><%= f.text_field :body %></div>
          <div class="book-edit-submit pt-4"><%= f.submit 'Update book',class: "submit-edit"%></div>
        <% end %>
          <div class="edit-link m-2">
            <div class="edit-show d-inline text-black">
              <%= link_to  book_path(@book.id),method: :get do %>
                <p class="d-inline pr-1 border-right border-dark">show</p>
              <% end %>
            </div>
            <div class="edit-back d-inline">
              <%= link_to  books_path,method: :get do %>
                <p class="d-inline pl-1">back</p>
              <% end %>
            </div>
          </div>
            <div class="edit-item text-center w-50 mx-auto p-4">
              <p>CopyRight Infratop.inc</p>
            </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
    <div class="row mt-4">
      <div class="col-3">
        <div class="col">
          <h1>User info</h1>
            <table class="table">
              <thead>
                <tr>
                  <th><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></th>
                  <th></th>
                </tr>
              </thead>
                <tbody>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                    <tr>
                      <td>introduction</td>
                      <td><%= @user.introduction %></td>
                    </tr>
                </tbody>
            </table>
          </div>
            <div class="col">
              <div class="profile-edit text-center">
                <%= link_to edit_user_path(@user), method: :get do %>
                   <p class="border border-dark rounded" style="color:black;"><i class="far fa-user"></i></p>
                <% end %>
              </div>
            </div>
              <div class="col">
                <h1>New book</h1>
                  <div class="user-show-form">
                    <%= form_for (@book_new) do |f| %>
                        <div class="show-form-title">Title</div>
                        <div class="show-form-title2"><%= f.text_field :title %></div>
                        <div class="show-form-opinion">Opinion</div>
                        <div class="show-form-opinion2"><%= f.text_area :body %></div>
                        <div class="show-form-submit"><%= f.submit 'Create Book', class: "submit-title" %></div>
                    <% end %>
                  </div>
              </div>
      </div>
         <div class="col-8">
                <div class="user-index-title">
                  <h1>users</h1>
                </div>
                 <table class="table">
                   <thead>
                     <tr>
                       <th>image</th>
                       <th>name</th>
                       <th></th>
                     </tr>
                   </thead>
                    <% @users.each do |user| %>
                         <tbody>
                           <td><%= user.name %></td>
                           <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
                           <td>
                            <%= link_to user_path(user.id), method: :get do %>
                              <p>show</p>
                            <% end %>
                           </td>
                         </tbody>
                    <% end %>
                </table>
              </div>
    </div>
  </div>

app/views/books/new.html.erb
<div class="error-message" style="color:green">
    <% if @book.errors.any? %>
    <%= @book.errors.count %> Error occurred
    <% @book.errors.full_messages.each do |message| %><br/>
      <%= message %>
    <% end %>
  <% end %>
</div>

<div class="container">
    <div class="row mt-4">
      <div class="col-3">
        <div class="col">
          <h1>User info</h1>
            <table class="table">
              <thead>
                <tr>
                  <th><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></th>
                  <th></th>
                </tr>
              </thead>
                <tbody>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                    <tr>
                      <td>introduction</td>
                      <td><%= @user.introduction %></td>
                    </tr>
                </tbody>
            </table>
          </div>
            <div class="col">
              <div class="profile-edit text-center">
                <%= link_to edit_user_path(@user), method: :get do %>
                   <p class="border border-dark rounded" style="color:black;"><i class="far fa-user"></i></p>
                <% end %>
              </div>
            </div>
              <div class="col">
                <h1>New book</h1>
                  <div class="user-show-form">
                    <%= form_for (@book_new) do |f| %>
                        <div class="show-form-title">Title</div>
                        <div class="show-form-title2"><%= f.text_field :title %></div>
                        <div class="show-form-opinion">Opinion</div>
                        <div class="show-form-opinion2"><%= f.text_area :body %></div>
                        <div class="show-form-submit"><%= f.submit 'Create Book', class: "submit-title" %></div>
                    <% end %>
                  </div>
              </div>
      </div>
              <div class="col-8">
                <div class="user-index-title">
                  <h1>users</h1>
                </div>
                 <table class="table">
                   <thead>
                     <tr>
                       <th>image</th>
                       <th>name</th>
                       <th></th>
                     </tr>
                   </thead>
                    <% @books.each do |book| %>
                         <tbody>
                           <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
                           <td>
                              <%= link_to book_path(book.id), method: :get do %>
                                <%= book.title %>
                              <% end %>
                           </td>
                           <td>
                             <%= book.body %>
                           </td>
                         </tbody>
                    <% end %>
                </table>
              </div>
    </div>
  </div>

app/views/books/show.html.erb
<div class="container">
    <div class="row mt-4">
      <div class="col-3">
        <div class="col">
          <h1>User info</h1>
            <table class="table">
              <thead>
                <tr>
                  <th><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></th>
                  <th></th>
                </tr>
              </thead>
                <tbody>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                    <tr>
                      <td>introduction</td>
                      <td><%= @user.introduction %></td>
                    </tr>
                </tbody>
            </table>
          </div>
            <div class="col">
              <div class="profile-edit text-center">
                <%= link_to edit_user_path(@user), method: :get do %>
                    <p class="border border-dark rounded" style="color:black;"><i class="far fa-user"></i></p>
                <% end %>
              </div>
            </div>
              <div class="col">
                <h1>New book</h1>
                  <div class="user-show-form">
                    <%= form_for (@book_new) do |f| %>
                        <div class="show-form-title">Title</div>
                        <div class="show-form-title2"><%= f.text_field :title %></div>
                        <div class="show-form-opinion">Opinion</div>
                        <div class="show-form-opinion2"><%= f.text_area :body %></div>
                        <div class="show-form-submit"><%= f.submit 'Create Book', class: "submit-title"%></div>
                    <% end %>
                  </div>
              </div>
      </div>
              <div class="col-8">
                <h1>Book detail</h1>
                  <table class="table">
                    <thead>
                      <tr>
                        <td class="w-20 text-center" style="width:20%;">
                          <div class="table-title" style="distroy:block;">
                            <div class="table-img"><%= attachment_image_tag @user, :profile_image, :fill, 100, 100,style: "width:50%;",fallback: "no_image.jpg" %></div>
                            <div class="table-name"><%= link_to user_path(@user.id), method: :get do %>
                              <%= @user.name %>
                            <% end %>
                            </div>
                          </div>
                        </td>
                        <td class="w-20 text-center">
                          <%= link_to book_path(@book.id), method: :get do %>
                            <%= @user.name %>
                          <% end %>
                        </td>
                        <td class="w-20 text-center"><%= @book.body %></td>
                        <% if @user == current_user %>
                        <div class="hidden">
                          <td class="w-20 text-center"><%= link_to 'Edit',edit_book_path %></td>
                          <td class="w-20 text-center"><%= link_to "Delete", books_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
                        </div>
                        <% end %>
                      </tr>
                    </thead>
                  </table>
              </div>
    </div>
  </div>

app/views/homes/about.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col text-center">
      <div class="about-title">
        <h1>Welcome to<i class="fas fa-book-open mb-4"></i><span style="weight:bold;">Bookers!</span></h1>
      </div>
        <div class="about-item text-center m-4">
          <p>CopyRight Infratop.inc</p>
        </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-4">
  <div class="row mx-auto w-50 mb-4">
    <div class="col">
      <div class="col">
        <h1>welcome to<i class="fas fa-book-open"></i><span class="top-page-font" style="font-weight:bold;">Bookers</span> !!</h1>
        <p class="py-1">in <i class="fas fa-book-open"></i><span style="weight:bold;">Bookers</span>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p class="py-1">about various books!</p>
      </div>
        <div class="col text-center  mx-auto">
          <div class="text-center w-75 mx-auto">
            <%= link_to new_user_session_path, method: :get do %>
              <p class="login-item">Log in</p>
            <% end %>
          </div>
          <div class="text-center w-75 mx-auto">
            <%= link_to new_user_registration_path,method: :get do  %>
              <p class="signup-item">Sign up</p>
            <% end %>
          </div>
        </div>
         <div class="col mx-auto w-50 text-center mt-4">
            <p>CopyRight Infratop.inc</p>
         </div>
    </div>
  </div>
</div>

app/views/layouts/_notification.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: #{key}) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
      <header class="shadow-sm">
        <nav class="navbar-expand-lg"style="background:black;">
          <div class="container">
            <div class="row">
              <h3 class="navbar-brand p-3 text-center" style="color:white;">Bookers</h3>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to user_path(current_user.id), method: :get do %>
                    <p class="m-2", style="color:white;"><i class="fas fa-home"></i>Home</p>
                    <% end %>
                  </li>
                    <li class="nav-item">
                      <%= link_to books_path, method: :get do %>
                      <p class="m-2", style="color:white;"><i class="fas fa-user-friends"></i></i></i>users</p>
                      <% end %>
                    </li>
                       <li class="nav-item">
                        <%= link_to users_path, method: :get do %>
                          <p class="m-2", style="color:white;"><i class="fas fa-book-open"></i>books</p>
                        <% end %>
                      </li>
                        <li class="nav-item">
                          <%= link_to destroy_user_session_path, method: :delete do %>
                          <p class="m-2", style="color:white;"><i class="fas fa-sign-out-alt"></i>logout</p>
                          <% end %>
                        </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to root_path,method: :get do %>
                    <p class="m-2", style="color:white;"><i class="fas fa-home"></i>Home</p>
                    <% end %>
                  </li>
                    <li class="nav-item">
                      <%= link_to about_path,method: :get do %>
                         <p class="m-2", style="color:white;"><i class="fas fa-link"></i>About</p>
                      <% end %>
                    </li>
                      <li class="nav-item">
                        <%= link_to new_user_registration_path,method: :get do %>
                           <p class="m-2", style="color:white;"><i class="fas fa-user-alt"></i>Sign up</p>
                        <% end %>
                      </li>
                        <li class="nav-item">
                          <%= link_to new_user_session_path, method: :get do %>
                             <p class="m-2", style="color:white;"><i class="fas fa-door-open"></i>Login</p>
                          <% end %>
                        </li>
                <% end %>
                </ul>
              </div>
            </div>
          </div>
        </nav>
    </header>
      <div class="flash-title">
         <% flash.each do |message_type, message| %>
          <%= message %>
        <% end %>
      </div>
      <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">
    <div class="row mt-4">
      <div class="col-3">
        <div class="col">
          <h1>User info</h1>
            <table class="table">
              <thead>
                <tr>
                  <th><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></th>
                  <th></th>
                </tr>
              </thead>
                <tbody>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                    <tr>
                      <td>introduction</td>
                      <td><%= @user.introduction %></td>
                    </tr>
                </tbody>
            </table>
          </div>
            <div class="col">
              <div class="profile-edit text-center">
                <%= link_to edit_user_path(@user), method: :get do %>
                   <p class="border border-dark rounded" style="color:black;"><i class="far fa-user"></i></p>
                <% end %>
              </div>
            </div>
              <div class="col">
                <h1>New book</h1>
                  <div class="user-show-form">
                    <%= form_for (@book_new) do |f| %>
                        <div class="show-form-title">Title</div>
                        <div class="show-form-title2"><%= f.text_field :title %></div>
                        <div class="show-form-opinion">Opinion</div>
                        <div class="show-form-opinion2"><%= f.text_area :body %></div>
                        <div class="show-form-submit"><%= f.submit 'Create Book', class: "submit-title"%></div>
                    <% end %>
                  </div>
              </div>
      </div>
         <div class="col-8">
                <div class="user-index-title">
                  <h1>users</h1>
                </div>
                 <table class="table">
                   <thead>
                     <tr>
                       <th></th>
                       <th>Title</th>
                       <th>Opinion</th>
                     </tr>
                   </thead>
                    <% @books.each do |book| %>
                         <tbody>
                           <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
                           <td>
                              <%= link_to book_path(book.id), method: :get do %>
                                <%= book.title %>
                              <% end %>
                           </td>
                           <td>
                             <%= book.body %>
                           </td>
                         </tbody>
                    <% end %>
                </table>
          </div>
    </div>
  </div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
  <div class="container">
    <div class="row mt-4">
      <div class="col-3">
        <div class="col">
          <h1>User info</h1>
            <table class="table">
              <thead>
                <tr>
                  <th> <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></th>
                  <th></th>
                </tr>
              </thead>
                <tbody>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                    <tr>
                      <td>introduction</td>
                      <td><%= @user.introduction %>s</td>
                    </tr>
                </tbody>
            </table>
          </div>
            <div class="col">
              <div class="profile-edit text-center">
                <%= link_to edit_user_path(@user), method: :get do %>
                    <p class="border border-dark rounded" style="color:black;"><i class="far fa-user"></i></p>
                <% end %>
              </div>
            </div>
              <div class="col">
                <h1>New book</h1>
                  <div class="book-show-form">
                    <%= form_for (@book_new) do |f| %>
                      <div class="book-show-title">Title</div>
                      <div class="book-show-title2"><%= f.text_field :title %></div>
                      <div class="book-show-opinion">Opinion</div>
                      <div class="book-show-opinion2"><%= f.text_area :body %></div>
                      <div class="book-show-submit"><%= f.submit 'Create Book', class: "submit-title" %></div>
                    <% end %>
                  </div>
              </div>
      </div>
        <div class="col-8">
          <h1>Books</h1>
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                </tr>
              </thead>
              <% @books.each do |book| %>
                <tbody>
                  <tr>
                    <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
                    <td>
                      <%= link_to book_path(book.id), method: :get do %>
                        <%= book.title %>
                      <% end %>
                    </td>
                    <td><%= book.body %></td>
                  </tr>
                </tbody>
              <% end %>
            </table>
        </div>
    </div>
  </div>